### ISSUE TITLE
Lack of proper documentation

### ISSUE THREAD

**Issue by AuthorShin** [vmorganp/Lazytainer#11]
Hello
Thanks for this cool project but I must say that it's lacking the proper documentation.

**Comment by vmorganp** [comment]
What, in your opinion, would you like changed?

**Comment by AuthorShin** [comment]
@vmorganp I would like to see a detailed explanation of how to setup and get the setup running and also with added known limitations like the one that I found on Reddit about not being able to put one of the containers in the shared network with another one when behind on a reverse proxy, also some examples and maybe videos about different container setup process.
Also, a detailed "How it does work" so that we know if it's safe to set it up on a public server, plus the ones where containers don't expose any ports publicly, but instead they use a docker network in share with the reverse proxy to confirm HTTPS on top of those containers and situations where server is also behind a Cloudflare proxy tunnel.

**Comment by vmorganp** [comment]
Is a document like that something you'd be willing to help write? It seems like you know what you're looking for and if you submit a PR to the readme I'll definitely work with you on it.

**Comment by AuthorShin** [comment]
@vmorganp Sure but the problem here is I don't understand the dynamic of Lazytainer myself to produce documents for it, that's where I need your help and detailed explanations first.

**Comment by vmorganp** [comment]
How's this?
https://github.com/vmorganp/Lazytainer#how-it-works

**Comment by arvigeus** [comment]
I think complete examples would be much more practical. For example caddy:

```
whoami.mysite.com {
    reverse_proxy lazytainer:81
}
```

**Comment by vmorganp** [comment]
@arvigeus I'm not sure what your example code is representing there, but there are complete examples using the whoami service as well as a Minecraft server. Is there another example or something missing you'd like to see?
