### ISSUE TITLE
Lazytainer default stopMethod being used despite configuration - documentation update?

### ISSUE THREAD

**Issue by calrock27** [vmorganp/Lazytainer#17]
I noticed that when starting up, Lazytainer is looking for stopMethod rather than sleepMethod as defined in the readme. After reviewing the groups.go file, it looks like the stopMethod is the same functionality intended for sleepMethod? 

https://github.com/vmorganp/Lazytainer/blob/671edc061fb905d38a9576205a12b8623906aeac/src/group.go#L27

![image](https://user-images.githubusercontent.com/46657562/219523475-e1b99a7b-47b7-4198-9c7e-7d24538b3089.png)

**Comment by vmorganp** [comment]
Should be fixed by https://github.com/vmorganp/Lazytainer/releases/tag/v2.0.1
