### ISSUE TITLE
Is there a way to make lazytainer "proxy" udp ports?

### ISSUE THREAD

**Issue by flx-666** [vmorganp/Lazytainer#56]
Hello,
I have a minecraft server working fine with lazytainer, but i struggle adding simple voice chat to it, which uses an udp port to work.
How can I have this udp port sent through lazytainer to the minecraft voice chat add on?
I have not been able to find info on udp ports in the doc...

Thanks in advance for your help !
Felix

**Comment by vmorganp** [comment]
Lazytainer doesn't distinguish between types of network traffic. 

You should just be able to add on the additional port after a comma like so
```
    - "lazytainer.group.<yourGroup>.ports=25565,<voiceChatPort>"
```

If that doesn't work for you, send me your docker compose and I can take a more thorough look.

**Comment by flx-666** [comment]
Hello,

Thanks for your help, I added the UDP port as you mentionned and everything is working flawlessly!
May I suggest you mention in the readme that the ports are not only tcp, but udp as well?

Apart from that, thanks for lazytainer, which is reeally useful and powerful

Felix

**Comment by vmorganp** [comment]
Where in the docs do you think that should go? 
You're also welcome to add it in a PR and I'll take a look.
